import { Inter } from 'next/font/google'
import './globals.css'
import './style.css'
import { UserProvider } from '../../context/user'
import AuthStateChangeProvider from '../../context/auth'
import { ChakraProvider } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='bg-[#f5f5f5]'>
      <ChakraProvider>
        <UserProvider>
          <AuthStateChangeProvider>
            <body className={inter.className}>{children}</body>
          </AuthStateChangeProvider>
        </UserProvider>
      </ChakraProvider>
    </html>
  )
}
